// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU6raWJPYoJCarWh9f2hbGn_2TOlDsIuw',
    appId: '1:1072672814476:web:8d14521d6476a95b7f52a9',
    messagingSenderId: '1072672814476',
    projectId: 'e-learning-a6dc0',
    authDomain: 'e-learning-a6dc0.firebaseapp.com',
    storageBucket: 'e-learning-a6dc0.appspot.com',
    measurementId: 'G-RFSQ2H22WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWT_01hdFi7fY-SBPevnFAumHKOWK8eXQ',
    appId: '1:1072672814476:android:7598e22f3765a6f47f52a9',
    messagingSenderId: '1072672814476',
    projectId: 'e-learning-a6dc0',
    storageBucket: 'e-learning-a6dc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-r-F_PddK4WK83QgRKngAeupaaZSqBAo',
    appId: '1:1072672814476:ios:f6edb1ab3932a7a37f52a9',
    messagingSenderId: '1072672814476',
    projectId: 'e-learning-a6dc0',
    storageBucket: 'e-learning-a6dc0.appspot.com',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-r-F_PddK4WK83QgRKngAeupaaZSqBAo',
    appId: '1:1072672814476:ios:f6edb1ab3932a7a37f52a9',
    messagingSenderId: '1072672814476',
    projectId: 'e-learning-a6dc0',
    storageBucket: 'e-learning-a6dc0.appspot.com',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU6raWJPYoJCarWh9f2hbGn_2TOlDsIuw',
    appId: '1:1072672814476:web:f9224cd66551b0347f52a9',
    messagingSenderId: '1072672814476',
    projectId: 'e-learning-a6dc0',
    authDomain: 'e-learning-a6dc0.firebaseapp.com',
    storageBucket: 'e-learning-a6dc0.appspot.com',
    measurementId: 'G-L8EZP8J44C',
  );
}
